# -*- coding: utf-8 -*-
"""Revisi Kode Jurnal Penambangan Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u60e6giNYUMvQzome7gR7Rf_lantdj8p
"""

# ================================
# HASIL DAN PEMBAHASAN - K-MEANS
# ================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

df = pd.read_csv('https://raw.githubusercontent.com/RizkyRamadhanAlf/Census-Income/refs/heads/main/Census.csv')

# 2. Ganti tanda '?' jadi NaN
df.replace('?', np.nan, inplace=True)

# CEK DATA KOSONG

missing_summary = pd.DataFrame({
    'Kolom': df.columns,
    'Jumlah Missing': df.isna().sum(),
    'Persentase (%)': (df.isna().sum() / len(df)) * 100
})

print("\nRingkasan Data Kosong:")
print(missing_summary)

# 3. Pisahkan numerik & kategorikal
num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

# 4. Imputasi missing value

imp_num = SimpleImputer(strategy='median')
imp_cat = SimpleImputer(strategy='most_frequent')
df[num_cols] = imp_num.fit_transform(df[num_cols])
df[cat_cols] = imp_cat.fit_transform(df[cat_cols])

# 5. Encoding kategorikal
encoder = LabelEncoder()
for col in cat_cols:
    df[col] = encoder.fit_transform(df[col])

# 6. Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

# 7. Menentukan jumlah cluster (Elbow)
inertia = []
K = range(2, 10)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(7,4))
plt.plot(K, inertia, 'bo-')
plt.title('Metode Elbow - Menentukan Jumlah Cluster Optimal')
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('WCSS (Within Cluster Sum of Squares)')
plt.grid(True)
plt.show()

# 8. Evaluasi Silhouette Score
for k in range(2, 10):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(X_scaled)
    sil = silhouette_score(X_scaled, labels)
    print(f"k={k}, Silhouette Score={sil:.3f}")

# 9. Clustering akhir (k=4)
kmeans_final = KMeans(n_clusters=4, random_state=42)
labels = kmeans_final.fit_predict(X_scaled)
df['Cluster'] = labels

# 10. PCA untuk visualisasi
pca = PCA(n_components=2)
reduced = pca.fit_transform(X_scaled)

plt.figure(figsize=(7,5))
plt.scatter(reduced[:,0], reduced[:,1], c=labels, cmap='viridis', s=10)
plt.title('Visualisasi Hasil Clustering Menggunakan PCA (k=4)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

# 11. Analisis ringkas tiap cluster
cluster_summary = df.groupby('Cluster').mean()
print(cluster_summary)

# 12. Visualisasi Heatmap untuk membandingkan klaster
plt.figure(figsize=(10,6))
sns.heatmap(cluster_summary, cmap='YlGnBu', annot=True, fmt=".2f")
plt.title("Perbandingan Rata-rata Fitur per Cluster")
plt.show()